In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/house_price.csv')

In [3]:
df.head()

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
1         2        80    Cool Town       300000
2         2        85  Normalville       150000
3         1        55  Normalville        78000
4         4       200     Skid Row       150000

In [4]:
df.head(3)

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
1         2        80    Cool Town       300000
2         2        85  Normalville       150000

Only the apartments that are bigger than 82sqrt meter

In [6]:
df_filtered = df [df ['sq_meter'] > 82]
df_filtered

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
2         2        85  Normalville       150000
4         4       200     Skid Row       150000