In [7]:
import pandas as pd

CSV_FILE = "jobs.csv"

df = pd.read_csv(CSV_FILE)
df["publication_date"] = pd.to_datetime(df["publication_date"])
df.head()

,id,year,keyword,title,employer,municipality,month,publication_date
0,995eca210f3eac097a3656cdbb0c83a8e2f89ff7,2026,AI,Senior VRED Visualization Artist,Avaron AB,Göteborg,5,2026-05-11
1,a1f5b1f0c9568c586691d89e77bb2aa46a5bd46c,2026,Backend,Junior Software Engineer,Avaron AB,Eskilstuna,5,2026-05-11
2,038d933643c62ceae871a3b8b175ddbcd3ec8ea2,2026,Cloud,Senior Application Security Architect,Avaron AB,Göteborg,5,2026-05-11
3,a59cc724e829c0a862acba38458c1561c0071e8f,2026,AI,Projektledare AI-Hubb,Stift Dalarna Science Park,Borlänge,5,2026-05-08
4,efaa81b451bb84201787596f1d529ead912ffbb7,2026,Cloud,SAP BTP Developer,Incluso AB,Skövde,5,2026-05-08

In [16]:
from datetime import datetime, timedelta

today = datetime.today()
last_week = today - timedelta(days=7)

In [17]:
df_last_week = df[df["publication_date"] >= last_week]
df_last_week.head(10)

,id,year,keyword,title,employer,municipality,month,publication_date
0,995eca210f3eac097a3656cdbb0c83a8e2f89ff7,2026,AI,Senior VRED Visualization Artist,Avaron AB,Göteborg,5,2026-05-11
1,a1f5b1f0c9568c586691d89e77bb2aa46a5bd46c,2026,Backend,Junior Software Engineer,Avaron AB,Eskilstuna,5,2026-05-11
2,038d933643c62ceae871a3b8b175ddbcd3ec8ea2,2026,Cloud,Senior Application Security Architect,Avaron AB,Göteborg,5,2026-05-11