Step 1: Identify and Handle Missing Values

Missing ages => average age of he user

Missing weight => average weight of he user

Missing heights => average heights of he user

Missing value in 'purchases' =>

In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
df = pd.read_json('./data.json')
df.head()

    user    age  height_cm  weight_kg        purchases  income
0  User1   25.0      175.0       70.0  [1, 0, 2, None]   40000
1  User2    NaN      160.0        NaN  [0, 1, None, 3]   25000
2  User3   35.0        NaN       85.0  [None, 2, 1, 0]   70000
3  User4   50.0      180.0       95.0  [3, None, 2, 1]   50000
4  User5  150.0      170.0      200.0     [2, 1, 0, 3]  120000

In [3]:
average_age = df['age'].mean()
average_height = df['height_cm'].mean()
average_weight = df['weight_kg'].mean()

In [4]:
print(average_age)
print(average_weight)

65.0
112.5

In [5]:
df['age'] = df['age'].fillna(round(average_age))
df['height_cm'] = df['height_cm'].fillna(round(average_height))
df['weight_kg'] = df['weight_kg'].fillna(round(average_weight))

In [6]:
df.head()

    user    age  height_cm  weight_kg        purchases  income
0  User1   25.0      175.0       70.0  [1, 0, 2, None]   40000
1  User2   65.0      160.0      112.0  [0, 1, None, 3]   25000
2  User3   35.0      171.0       85.0  [None, 2, 1, 0]   70000
3  User4   50.0      180.0       95.0  [3, None, 2, 1]   50000
4  User5  150.0      170.0      200.0     [2, 1, 0, 3]  120000

In [7]:
def clean_purchases(purchases):
  return [0 if p is None else p for p in purchases]

df['purchases'] = df['purchases'].apply(clean_purchases)

df.head()

    user    age  height_cm  weight_kg     purchases  income
0  User1   25.0      175.0       70.0  [1, 0, 2, 0]   40000
1  User2   65.0      160.0      112.0  [0, 1, 0, 3]   25000
2  User3   35.0      171.0       85.0  [0, 2, 1, 0]   70000
3  User4   50.0      180.0       95.0  [3, 0, 2, 1]   50000
4  User5  150.0      170.0      200.0  [2, 1, 0, 3]  120000

Step 2: Processing Outliers

In [8]:
max_age = 100
max_weight = 150

In [9]:
df['age'] = df['age'].apply(lambda x: min(x, max_age))
df['weight_kg'] = df['weight_kg'].apply(lambda x: min(x, max_weight))
df.head()

    user    age  height_cm  weight_kg     purchases  income
0  User1   25.0      175.0       70.0  [1, 0, 2, 0]   40000
1  User2   65.0      160.0      112.0  [0, 1, 0, 3]   25000
2  User3   35.0      171.0       85.0  [0, 2, 1, 0]   70000
3  User4   50.0      180.0       95.0  [3, 0, 2, 1]   50000
4  User5  100.0      170.0      150.0  [2, 1, 0, 3]  120000

Step 3: Normalization the Data

In [10]:
max_height = df['height_cm'].max()
max_weight = df['weight_kg'].max()
max_income = df['income'].max()

In [11]:
max_height = max_height if max_height !=0 else 1
max_weight = max_weight if max_weight !=0 else 1
max_income = max_income if max_income !=0 else 1

In [12]:
df['height_cm'] = df['height_cm'] / max_height
df['weight_kg'] = df['weight_kg'] / max_weight
df['income'] = df['income'] / max_income

In [13]:
df[['user', 'height_cm', 'weight_kg', 'income']].head()

    user  height_cm  weight_kg    income
0  User1   0.972222   0.466667  0.333333
1  User2   0.888889   0.746667  0.208333
2  User3   0.950000   0.566667  0.583333
3  User4   1.000000   0.633333  0.416667
4  User5   0.944444   1.000000  1.000000

One_hot_encoding

In [14]:
df_new = './cleaned_data.json'
df.to_json(df_new, orient='records', indent=4)